### ISSUE TITLE
new ENV tls_trust_file

### ISSUE THREAD

**Issue by pepeshark** [tiredofit/docker-debian#1]
Hi,
I would like to set up tls_trust_file in msmtp conf file from docker ENV.
Can you add this tls_trust_file conf parameter in this file? 
https://github.com/tiredofit/docker-debian/blob/buster/install/etc/cont-init.d/04-smtp

**Comment by tiredofit** [comment]
Can you post an example msmtp config file with this directive in it? This should be no problem after I see an example.

**Comment by pepeshark** [comment]
Sure.
You can see my present config.

```defaults
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile /var/log/msmtp.log```

**Comment by tiredofit** [comment]
OK! That's easy enough to do. I've added it for you - It's going to take some time for the images to build on Docker Hub. Freepbx will also rebuild itself on its own - but won't assign a new tag to it, so you'll have to rely on freepbx/15-latest pulls. 

Let me know if this works out for you.

**Comment by pepeshark** [comment]
Thanks.
As I can see debian image was builded yesterday.
I will check freepbx image on this page https://hub.docker.com/r/tiredofit/freepbx/builds then I will let you know about test.

**Comment by pepeshark** [comment]
@tiredofit 
do you have any prediction when will be builded the freepbx image? 
As I can see th last build date is October 28, 2019 06:34 PM.
Thanks.

**Comment by tiredofit** [comment]
Let me go and see what the queue looks like, it seems like its been building for days. If all else fails I'll go and build a copy for you and push manually.

**Comment by tiredofit** [comment]
The build was failing, It is ready now! Let me know.

**Comment by pepeshark** [comment]
Sorry I forgot that freepbx base image is nodejs and debian scretch. I think you should rebuild this image too https://hub.docker.com/r/tiredofit/nodejs/builds
Then freepbx again. Please do it :)

**Comment by tiredofit** [comment]
Give it a try now, for some reason the Node dependent image didn't build (Docker Hub tends to do this for the free tier) - There is a fresh build of Freepbx in there now.

**Comment by pepeshark** [comment]
It is not working.
There is a misstake in variable name.
`    if [ -n "$SMTP_TLSTRUSTFILE" ]; then echo 'tls_trust_file '$SMTP_TLS_TRUST_FILE >> /etc/msmtprc; fi`

The right one is like this:
`    if [ -n "$SMTP_TLS_TRUST_FILE" ]; then echo 'tls_trust_file '$SMTP_TLS_TRUST_FILE >> /etc/msmtprc; fi`

Can you fix it and rebuild please? :)

**Comment by tiredofit** [comment]
Jeez, after all of that. I will built them all manually for you. Will let you know.

**Comment by tiredofit** [comment]
OK, I've manually built all three images and pushed to Docker Hub. Let me know?

**Comment by pepeshark** [comment]
I tested fully featured. It's working well.
Thank you so much. :)
