### ISSUE TITLE
Commenting out echos creates empty conditional blocks

### ISSUE THREAD

**Issue by jmturner** [tiredofit/docker-debian#25]
In lines 290-293 of your Dockerfile, you use sed to comment out echo statements in the s6-overlay scripts:
```
    sed -i "s|echo|# echo |g" /package/admin/s6-overlay/etc/s6-rc/scripts/cont-init && \
    sed -i "s|echo|# echo |g" /package/admin/s6-overlay/etc/s6-rc/scripts/cont-finish && \
    sed -i "s|echo ' (no readiness notification)'|# echo ' (no readiness notification)'|g" /package/admin/s6-overlay/etc/s6-rc/scripts/services-up && \
    sed -i "s|s6-echo -n|# s6-echo -n|g" /package/admin/s6-overlay/etc/s6-rc/scripts/services-up && \
```
This creates empty conditional blocks (removing the only thing in the block) and the scripts then fail with a "fi unexpected" error.

> /package/admin/s6-overlay-3.1.3.0/etc/s6-rc/scripts/cont-init: 18: Syntax error: "fi" unexpected

Either the echos need to remain or the conditional blocks commented out/removed as well.

**Comment by tiredofit** [comment]
Ack - Thanks for catching this. It is resolved on the other base image "tiredofit/alpine" but I must have forgotten on this one. Let me issue new versions asap.

**Comment by tiredofit** [comment]
OK - in place. Takes 15 minutes "ish" to build this one, and I will proceed with building `tiredofit/nginx` and `tiredofit/nginx-php-fpm` as they are most used. 

https://github.com/tiredofit/docker-debian/releases/tag/7.7.48

**Comment by tiredofit** [comment]
OK - all built! Thanks for the report.
